safe: true
lsi: false
source: .
name: swiftpoetry.com 
author: krzysztof siejkowski
deployurl: https://swiftpoetry.com

future: true
permalink: :title

exclude: [CNAME, Gemfile, Gemfile.lock, README.md]

highlighter: rouge
markdown: kramdown

